name: Update subconverter

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * *
   
jobs:
  Build:
    name: Build and Update
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare
      run: |
        cd /tmp
        git clone https://github.com/tindy2013/subconverter.git
    - name: Build
      run: docker run -v /tmp/subconverter:/root/workdir multiarch/alpine:amd64-latest-stable /bin/sh -c "apk add bash git nodejs npm && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
    - name: Clean up
      run: |
        sudo rm -rf subconverter
        mv -f /tmp/subconverter/subconverter subconverter
        mv -f subconverter/subconverter subconverter/subconverter.exe
        sudo chmod +x subconverter/subconverter.exe
    - name: Modify pref.ini
      run: |
        sudo cp -rf files/* subconverter/
    - name: Add & Commit
      uses: EndBug/add-and-commit@v6
      with:
        author_name: GitHub Action
        author_email: noreply@github.com
        message: "Update subconverter"
        add: "-A"
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
